apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-replicaset
  labels: 
    app: myapp 
spec: 
    selector:
      matchLabels:
        env: production
    replicas: 3
    template:
      metadata:
        name: nginx
        labels: 
          env: production
      spec: 
        containers:
          - name: nginx
            image: nginx